# BOOSTING

<ul>
    <li>Can be used for both regression and classification.</li>        
    <li>Helps reduce variance and bias.</li>
    <br>
    <li>In <strong>Bagging</strong> the algorithm creates  multiple copies of the original data and constructs several decision trees on the copies and combines all the trees to make predictions.</li>
    <ul>
        <strong>
            <li>
                WE CONSTRUCT THESE TREES INDEPENDENTLY!!!
            </li>
        </strong>
    </ul>
    <br>
    <li>In <strong>Boosting</strong> the decision trees are grown sequentially (sequential algorithm). Each tree is grown using information from previously grown trees.
    <ul>
        <strong>
            <li>
                THE TREES ARE NOT INDEPENDENT FROM EACH OTHER!!!
            </li>
        </strong>
    </ul>  
    </li>
</ul>
<br>
It is based on a rather counter-intuitive theory: A weak learner is not able to make good predictions. <br>
<ul>
    <li>A weak learner is just a little better someone who guesses randomly (like coin flip). For example: Decision Trees with depth 1.</li>
    <li>Combining weak learners can prove to be an extremely powerful classifier !!!</li>
    <li style="color:red;font-weight:bold">By fitting small trees (<strong>decision stumps</strong>) we slowly improve the final result in case it doesn't perform well.
        <ul>
            <li>We use adaptive boosting. <strong style="color:green">Adaboost algorithm!!!</strong></li>
        </ul>
    </li>
    <br>
    <li>Used in OpenCV: Viola-Jones face detection algorithm.</li>
</ul>



# Boosting illustration 

<strong>Boosting</strong> combines very simple weak learners such as <strong>decision trees</strong> with depth <strong>1</strong> (capable of linear classification).<br>
<img src = "./Images/boosting1.png"/>
<p>1. We want to end with with a seperation of the green dots and yellow dots.</p>
<img src= "https://github.com/nndr229/MachineLearningBasics/blob/main/Images/boosting2.png" style="width:300px;"/>
<p>2. The classifier made 2 mistakes as 2 yellow dots are misclassified.</p>
<p>3. In the next iteration it will focus on the misclassified items.
    <ul>
        <li>A weight <strong>w</strong> has been already assigned to every single sample in the dataset.</li>
        <li>Increase the weights <strong>w</strong> for the misclassified items.</li>
        <li>Decrease the weights <strong>w</strong> for the correctly classified items.</li>
    </ul>
</p>
<p>We can't use a straight line as this is not a linearly seperable problem.</p>
<img src = "boosting3.png" style="width:300px"/>
<p>4. In the next iteration the algorithm correctly classifies a yellow dot that was previously misclassified.</p>
<p>5. In the next iteration the algorithm will focus on the last misclassified dot.</p>
<img src = "Images/boosting4.png" style="width:300px"/>
<p style="color:green;font-weight:bold">The algorihtm has come up with 3 weak but simple decision tree learners to classify this dataset accurately (a non-linear decision boundary has been found sequentially).WE JUST HAVE TO COMBINE THESE CLASSIFIERS !!!</p>
<img src = "Images/boosting5.png" style="width:300px"/>


# Boosting Equations 

<img src = "Images/equation.png" style="width:300px"/>
<p style="text-align:center;font-weight:bold">Sign Function</p>
<h4 style="">$H(x) \  =  \ sign \sum_{i=1}^n \alpha_i \ h_i(x)$</h4>
<ul style="text-align:center;line-width:10px"><br>
    <li style="text-align:left;">Final model $H(x)$ is a strong classifier.</li><br>
    <li style="text-align:left">We keep combining $h_i(x)$ :weak learners that only know to calssify part of the full space.</li><br>
     <li style="text-align:left">We use $\alpha_i$ parameters to control the importance of each $h_i(x)$ .</li><br>
    <li style="text-align:left">We assign $+1$ and $-1$ for the output classes(yellow and green).</li><br>
    <li style="text-align:left">We initialize the weight parameters $w_i = \frac{1}{N}$  for every single sample in the dataset.</li><br>
        <li style="text-align:left">$\sum_{i=1}^n$ : We make sure this is a distribution.</li><br>
    <li style="text-align:left">$\epsilon = \sum_{wrong}w_i$ : error is the sum of the misclassified weights.</li><br>
</ul>

<strong>STEPS</strong>
<ol>
    <li>Initialize the weight parameters: <span style="color:red;font-size:15px">$w_i = \frac{1}{N}$</span> </li><br>
    <li>Pick $h_t(x)$ that minimizes $ \ \epsilon \ $ error term: <span style="color:red;font-size:15px"> $\epsilon_t = \sum_{wrong}w_i$</span></li><br>
    <li>Calculate $a_t$: <span style="color:red;font-size:15px">$a_t = \frac{1}{2}\ln(\frac{1-\epsilon_t}{\epsilon_t})$</span></li><br>
    <li>Update $w_{t+1}$: <span style="color:red;font-size:15px">$w_i^{t+1} = \frac{w_i^t}{Z} e^{-\alpha_t h_t(x) y(x)}$</span></li><br>
    <li>Go back to Step 2 and repeat.</li><br>
<ol>
<p>In every iteration we add a new $h(x)$ or weak learner to the final model.</p>

## $\alpha$ parameter

<img src = "Images/alpha.png" style="width:300px"/>
<p style="text-align:center;font-size:20px">$a_t = \frac{1}{2}\ln(\frac{1-\epsilon_t}{\epsilon_t})$</p>
<ul>
    <li>Given an $h(x)$ calssifier the $\alpha$ value increases as the error converges to 0 (good classifiers are given more weight.).</li>
    <li>Given an $h(x)$ calssifier the $\alpha$ value is 0 if the error is 0.5. Beacause it is a random guess like a coin toss(we do not want to rely on random guesses).</li>
    <li>We give a negative $\alpha$ value for $h(x)$ calssifiers that are worse than random guesses meaning the error rate is greater than 0.5 .</li>
</ul>

## $w$ parameter

<p style="text-align:center;font-size:20px">$w_i^{t+1} = \frac{w_i^t}{Z} e^{-\alpha_t h_t(x) y(x)}$</p>
<ul>
    <li>We use the equation to update weights in every iteration.</li>
    <li>we use higher weights for for more important samples and vice versa.</li>
    <li>The $Z$ makes sure $w$ is a distribution so that the sum is 1.</li>
    <li>$y(x)$ flips the sign of the exponent if $h(x)$ is wrong. This is good as it assigns higher weights to misclassified samples and smaller weights for correctly classified samples.
    <ul>
        <li>In the next iteration the $h(x)$ learner can focus on those samples with higher weights.</li>
    </ul>
    </li>
    <li>Why use $\alpha$ in the formula? We use $\alpha$ value to make sure that a classifier that predicts more correctly become more imporatant.</li>
</ul>

# <span style="color:purple">CODE (IRIS DATASET)</span>

In [5]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn import datasets

In [9]:
iris_data = datasets.load_iris()

features = iris_data.data
targets = iris_data.target

feature_train, feature_test, target_train, target_test = train_test_split(features, targets, test_size=.2)

In [10]:
#We use Ada-Boost

#We usually set the base estimator as a decision tree.

# n_estimators: Here: the number of decision trees.
#               The maximum number of estimators at which boosting is terminated. 
#               In case of perfect fit, the learning procedure is stopped early.

#learning_rate: Learning rate shrinks the contribution of each classifier by learning_rate. 
#               There is a trade-off between learning_rate and n_estimators.

#random_state: Controls the random seed given at each base_estimator at each boosting iteration.

model = AdaBoostClassifier(n_estimators=100, learning_rate=1, random_state=123)
model.fitted = model.fit(feature_train, target_train)
model.predictions = model.fitted.predict(feature_test)

In [11]:
print("Confusion matrix is : ")
print(confusion_matrix(target_test, model.predictions))
print(f"Accuracy score is : {accuracy_score(target_test, model.predictions)}")

Confusion matrix is : 
[[11  0  0]
 [ 0 10  1]
 [ 0  0  8]]
Accuracy score is : 0.9666666666666667


# <span style="color:purple">CODE (WINE DATASET)</span>

In [12]:
import pandas as pd
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn import preprocessing

In [14]:
def is_tasty(quality):
    if quality >= 7:
        return 1
    else:
        return 0

data = pd.read_csv("../../PythonMachineLearning_HolczerBalazs/Datasets/Datasets/wine.csv", sep=";")

In [15]:
features_wine = data[
    ["fixed acidity", "volatile acidity", "citric acid", "residual sugar", "chlorides", "free sulfur dioxide",
     "total sulfur dioxide", "density", "pH", "sulphates", "alcohol"]]
data['tasty'] = data["quality"].apply(is_tasty)
targets_wine = data['tasty']

In [18]:
#our features
print(features_wine[0:1])

   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   

   free sulfur dioxide  total sulfur dioxide  density   pH  sulphates  alcohol  
0                 45.0                 170.0    1.001  3.0       0.45      8.8  


In [20]:
#our targets
print(targets_wine)

0       0
1       0
2       0
3       0
4       0
       ..
4893    0
4894    0
4895    0
4896    1
4897    0
Name: tasty, Length: 4898, dtype: int64


In [30]:
X = np.array(features_wine).reshape(-1, 11)
y = np.array(targets_wine)
# X = preprocessing.MinMaxScaler().fit_transform(X)
#When we use preprocessing we find that our accuracy reduces.
#We need minMaxScaler for kNN . For boosting we should avoid this.

In [31]:
feature_train_w, feature_test_w, target_train_w, target_test_w = train_test_split(features_wine, targets_wine, test_size=.2)

param_dist = {
    'n_estimators': [10, 50, 200],
    'learning_rate': [0.01, 0.05, 0.3, 1],
}

estimator = AdaBoostClassifier()

In [32]:
grid_search = GridSearchCV(estimator=estimator, param_grid=param_dist, cv=10)
grid_search.fit(feature_train_w, target_train_w)

predictions_wine = grid_search.predict(feature_test_w)

In [33]:
print("Confusion matrix is : ")
print(confusion_matrix(target_test_w, predictions_wine))
print(f"Accuracy score is : {accuracy_score(target_test_w, predictions_wine)}")

Confusion matrix is : 
[[743  45]
 [111  81]]
Accuracy score is : 0.8408163265306122


<p style="color:red;font-size:14px;font-weight:bold">Bagging is preffered over Boosting for decision trees as it reduces variance and solves over-fitting. Boosting reduces bias but has some tendency to over-fit.</p>

# <span style="color:darkgreen">END</span>