# DECISION TREES

<ul>
    <li>Supervised learning algorithm mostly used in classification but can be used for regression as well as they work well for both categorical(like sunny,cloudy,rainy) and continuous output(numercial values like 87.2342,234.234).</li>
    <li>Very similar to search trees.</li>
    <li>Splits the data into two or more homogeneous sets based on splitter in input variables.</li>
 </ul>
 <h4>We have a single feature <strong>x</strong>, the number of hours a student spends studying. We want to predict the probability <strong>y</strong> that he/she will pass an exam.</h4>
<ul>
    <li><strong>Categorical Variable Decision Tree:</strong> variable such as fail/pass or yes/no.</li>
    <li><strong>Continuous Variable Decision Tree:</strong> continuous variables like the ones used in regression.</li>
</ul>
<img src = "Images/categoricaldt.png" style="width:600px;"/>
<ul>
    <li><strong style="color:green">ROOT NODE : </strong>Represents the entire dataset/population and this further gets divided into several subsets (The root node corresponds to the best predictor).</li>
    <li><strong style="color:#ECCC15">LEAF NODES : </strong>Nodes that have no children. These are the values that we are after! Our output(s)!</li>
    <li><strong style="color:steelblue">DECISION NODES : </strong>The algorithm spkits the node into Sub-nodes based on the given dataset.</li>
</ul>
<img src ="Images/dt.png" style="width:500px"/>
<p>The decision tree classifier depends heavily on splits.<br>There are several algorithms for this problem.<br>
<ul>
    <li>Gini Index Approach.</li>
    <li>Calculating the information entropy(ID3 algorithm or C4.5 approach).</li>
    <li>Algorithm based in variance reduction.</li>
</ul>
</p>

## Example of Categorical Decision Tree

<p>Image from Holczer Balazs's course on ML(UDEMY)</p>
<p>DATSET PREDICTING WHETHER TO PLAY GOLF OR NOT BASED ON WAETHER.</p>
<img src="Images/cdt.png">
<p>We have to decide what is going to be the root node? What are the branches ? and so on...</p>

# ID3 algorithm and Shannon Entropy

<p>Usually <strong>ID3</strong> algorithm is used to build the decision tree ~ it is a top down greedy search of all possible branches.<br>
It uses <strong>entropy</strong> and <strong>information gain</strong> to build the tree.
</p>
The $H(x)$ , Shannon entropy of a discrete random variable $X$ with possible values $x_1,x_2,...,x_n$ and probability mass function $P(x)$ is defined as : <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; $H(X) = -\sum_{i}^n P(x_i)\log_2P(x_i)$<br><br>
<a href="https://en.wikipedia.org/wiki/Entropy_(information_theory)">Go here for more info about Shannon Entropy (See Example)</a>.<br>
<p style="font-weight:bold;color:red">A BRANCH WITH ENTROPY MORE THAN 1 REQUIRES SPLITTING!!!<br>
    <li style="font-weight:bold;color:red"> Root node has the maximum information gain(entropy reduciton).</li>
    <li style="font-weight:bold;color:red"> Leaf nodes have entropy 0.</li>
</p>
<p>Consider the golf dataset.</p>
<p>Playing Golf:
    <li>9 Times YES</li>
    <li>5 Times NO</li>
    <li>$H(Playing  \ Golf) = H(9,5) = -(0.64 \log_2{0.64}) -(0.36 \log_2{0.36}) \  = \ 0.94 $</li>
</p>


### Importance of features 

**We have to be able  to calculate the entropy wrt a given feature to be able to calculate information gain.** <br>
$E(T,X) = \sum_{x} P(x)E(x)$<br>

<table>
    <thead>
        <tr>
            <td></td>
            <td style="font-weight:bold; background:steelblue;color:white"></td>
            <td style="font-weight:bold; background:steelblue;color:white">YES</td>
            <td style="font-weight:bold;  background:steelblue;color:white">NO</td>
        </tr>
    </thead>
    <tbody>
        <tr>
          <td ></td>
          <td style="font-weight:bold;background:steelblue;color:white">Sunny</td>
          <td>2</td>
          <td>3</td>
        </tr>
        <tr>
          <td style="font-weight:bold">OUTLOOK</td>
          <td style="font-weight:bold;background:steelblue;color:white">Overcast</td>
          <td>4</td>
          <td>0</td>
        </tr>  
        <tr>
          <td ></td>
          <td style="font-weight:bold;background:steelblue;color:white">Rainy</td>
          <td>3</td>
          <td>2</td>
        </tr>  
    </tbody>
</table>
<p style="text-align:center;font-weight:bold"><em>E(PlayGolf,Outlook)</em> = P(Sunny)E(2,3) +  P(Overcast)E(4,0) +  P(Rainy)E(3,2)</p>
<p style="text-align:center;font-weight:bold"> = $\frac{5}{14}*0.971 + \ \frac{4}{14}*0 + \ \frac{5}{14}*0.971  \ \ = \ \ 0.6936$</p>

<h3>What about information gain?</h3>
<p>It is the decrease in entropy after a dataset is split on an attribute/feature.</p>
<li>Feature/attribute with the highest information gain will be the root node.</li>
<p style="font-weight:bold;color:red"> Information Gain(Outlook) = H(Play Golf) - E(Play Golf, Outlook) = 0.94 - 0.693 = "0.247" (HIGHEST)</p>
<p style="font-weight:bold;color:green"> Information Gain(Temperature) = H(Play Golf) - E(Play Golf, Temperature)= "0.029"</p>
<p style="font-weight:bold;color:green"> Information Gain(Humidity) = H(Play Golf) - E(Play Golf, Humidity)= "0.152"</p>
<p style="font-weight:bold;color:green"> Information Gain(Wind) = H(Play Golf) - E(Play Golf, Wind)= "0.048"</p>

# Gini Index Approach

<p><strong>CART</strong>(Classification and Regression Tree) algorithm uses Gini index to decide how to make splits.<br>
<ul>
    <li>Gini Index approach is a little bit better than calculating the information gain and entropy.(THE ALGORITHMS ARE APPROXIMATELY THE SAME!!!)</li>
    <li>When dealing with entropy we have to calculate logarithms ,which is computationally expensive. So we prefer Gini index approach.</li>
</ul>
</p>
<p>Formula used to calculate the gini index of an <strong>X</strong> random variable.</p><br>
$G(X) = 1 - \sum_{i=1}^n {P(x_i)^2} \ \ $ Where n is the number of output classes<br><br>

$E(s,t) = G(t) -  P(left)G({left}_t) - P(right)G(right_t) $<br><br>
<strong style="color:red">We have to calculate this E value to know which features to split.</strong>
<strong style="color:red">We split the feature with the lowest Gini Index.</strong>
<p>Consider the golf dataset again.</p>
<p>Playing Golf:
    <li>9 Times YES</li>
    <li>5 Times NO</li>
    <li><strong>G</strong>$(Playing \ Golf) = 1 - (0.64)^2 - (0.36)^2 = 0.46 $</li>
</p>
<p>Think that we are dealing with the credit scoring dataset. So the <strong>target variable is WILL DEFAULT / WILL NOT DEFAULT.</strong></p>
$E(s,t) = G(t) -  P(left)G({left}_t) - P(right)G(right_t) $<br><br>
<strong>Where</strong>
<ul>
    <li>$G(t)$ is the Gini Index for node t.</li>
    <li>$P(left)G({left}_t)$ is the proportion/probability of observation in the left node after splitting times Gini index of the left node after splitting.</li>
    <li>$P(right)G(right_t)$ is the proportion/probability of observation in the right node after splitting times Gini index of the right node after splitting.</li>
</ul>

<table>
    <thead>
        <tr>
            <td></td>
            <td style="font-weight:bold; background:steelblue;color:white"></td>
            <td style="font-weight:bold; background:steelblue;color:white">YES</td>
            <td style="font-weight:bold;  background:steelblue;color:white">NO</td>
        </tr>
    </thead>
    <tbody>
        <tr>
          <td style="font-weight:bold;">GENDER</td>
          <td style="font-weight:bold;background:steelblue;color:white">Male</td>
          <td>3</td>
          <td>2</td>
        </tr>
        <tr>
          <td style="font-weight:bold"></td>
          <td style="font-weight:bold;background:steelblue;color:white">Female</td>
          <td>2</td>
          <td>0</td>
        </tr>   
    </tbody>
</table>
<p> $G(t) =  1 - (\frac{7}{9})^2 - (\frac{2}{9})^2 \ \ = 0.3432$</p>
<p> $G(male) = 1 - (\frac{3}{5})^2 - (\frac{2}{5})^2 \ \ = 0.48$</p>
<p> $G(female) = 1 - (\frac{4}{4})^2 - (\frac{0}{5})^2 \ \ = 0$</p>
<p> $E(s,t) = 0.34 - \frac{5}{9}*0.48 - \frac{4}{9}*0 \ \ = 0.07$</p>

## Advantages and Disadvantages of Discision Trees

<strong style="color:green">Advantages</strong>
<ul>
<li>One of the best approaches to identify most significant variables and the relationship between them.</li>
<li>No need for data-preprocessing.Not influenced by outliers.</li>
<li>Can handle numberical and categorical variables.</li>
</ul>
<strong style="color:red">Disadvantages</strong>
<ul>
<li>Have a tendency to overfit because we solve it by pruning.</li>
<li>Unstable because a small variation in the data might result in a completely different trre being generated.Generating the optimal tree like structure is NP-complete , so we use a greedy approach.</li>
</ul>

# <span style="color:purple">CODE for Decision Tree On Iris Dataset</span> 

In [53]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_validate
from sklearn import datasets

In [54]:
iris_data = datasets.load_iris()

features = iris_data.data
targets = iris_data.target

#train_test_split
feature_train, feature_test, target_train, target_test = train_test_split(features, targets, test_size=.2)

In [55]:
#criterion passed as a parameter to the clsasifier can something like gini or entropy. Default is gini.
model = DecisionTreeClassifier(criterion="gini")

#we use cross-validation
predicted = cross_validate(model, features, targets, cv=10)
print(f"Predicted mean score(across 10 folds) for our decision tree our classifier {np.mean(predicted['test_score'])}")

Predicted mean score(across 10 folds) for our decision tree our classifier 0.96


<h2>Tree Constructed by scikit learn using Entropy model.</h2>
<img src = "Images/outtree2.png"/>

# <span style="color:purple">Parameter Tuning for Decision Tree On Iris Dataset</span> 

In [56]:
#Grid search for parameter tuning
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [57]:
#parameter grid with values from 1 - 9
param_grid = {'max_depth': np.arange(1, 10)}

tuned_tree = GridSearchCV(DecisionTreeClassifier(), param_grid,cv=3,iid=False)

tuned_tree.fit(feature_train, target_train)

print("Best parameter with Grid Search: ", tuned_tree.best_params_)

Best parameter with Grid Search:  {'max_depth': 4}


In [58]:
#make predicitons
grid_predictions = tuned_tree.predict(feature_test)

print("Confusion matrix: ")
print(confusion_matrix(target_test, grid_predictions))
print()
print("Accuracy score: ")
print(accuracy_score(target_test, grid_predictions))

Confusion matrix: 
[[12  0  0]
 [ 0 11  0]
 [ 0  0  7]]

Accuracy score: 
1.0


**We could achieve an accuracy of 100% with parameter tuning!!!**

# <span style="color:purple">Identifying Cancer with Decision Trees</span> 

In [59]:
#Predict whether malignant with 0 or benign with 1
#There are 30 features in the dataset

cancer_data = datasets.load_breast_cancer()

features_cancer = cancer_data.data
labels_cancer = cancer_data.target

feature_train_c, feature_test_c, target_train_c, target_test_c = train_test_split(features_cancer, labels_cancer, test_size=0.3)

In [60]:
model_cancer_gini = DecisionTreeClassifier(criterion='gini', max_depth=5)

predicted_c_gini = cross_validate(model_cancer_gini, features_cancer, labels_cancer, cv=10)
print(np.mean(predicted_c_gini['test_score']))

0.9105760089879871


In [61]:
model_cancer_entropy = DecisionTreeClassifier(criterion='entropy', max_depth=5)

predicted_c_entropy = cross_validate(model_cancer_entropy, features_cancer, labels_cancer, cv=10)
print(np.mean(predicted_c_entropy['test_score']))

0.9439104226082448


**We can see that we got a better accuracy score using the "entropy model" for this dataset.**

# <span style="color:darkgreen">END</span>